name: oxygen
version: '${project.version}'
main: org.leafd.oxygen.Oxygen
api-version: '1.19'
dependencies:
  server:
    PlaceholderAPI:
      # Load order is relative to the dependency. So here PlaceholderAPI loads before our plugin.
      load: BEFORE
      required: false